# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 07:21
from __future__ import unicode_literals

import applications.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDevUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=25, validators=[django.core.validators.RegexValidator(regex='[A-Za-z]{2,3}[0-9]{1,5}@cornell.edu')], verbose_name='Email')),
                ('on_email_list', models.BooleanField(default=False, verbose_name='On Email List?')),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2019, message='The year specified is too high'), django.core.validators.MinValueValidator(2016, message='The year specified is too low')], verbose_name='Year')),
                ('major', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DES', 'Designer'), ('DEV', 'Developer')], default='DEV', max_length=20, verbose_name='Role')),
                ('essay', models.CharField(blank=True, default='', max_length=100000, validators=[applications.models.validate_essay_length], verbose_name='Candidate Essay')),
                ('portfolio_link', models.CharField(default='', max_length=200, verbose_name='Portfolio Link')),
                ('resume_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Resume Link')),
                ('access_code', models.CharField(blank=True, max_length=64, verbose_name='Rand64 Access Code')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="The score can't be lower than 0"), django.core.validators.MaxValueValidator(10, message="The score can't be higher than 10")], verbose_name='Preference Score')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.CharField(max_length=255, verbose_name='Idea Text')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_cs_course', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(7000, message='The course number you entered is too high'), django.core.validators.MinValueValidator(1000, message='The course number you entered is too low')], verbose_name='Highest CS Course')),
                ('essay', models.CharField(blank=True, default='', max_length=100000, validators=[applications.models.validate_essay_length], verbose_name='Trainee Essay')),
                ('portfolio_link', models.CharField(blank=True, default='', max_length=200, verbose_name='Portfolio Link')),
                ('resume_link', models.CharField(blank=True, max_length=200, verbose_name='Resume Link')),
                ('access_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Rand64 Access Code')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message="The score can't be lower than 0"), django.core.validators.MaxValueValidator(10, message="The score can't be higher than 10")], verbose_name='Preference Score')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status Notes')),
            ],
        ),
        migrations.AddField(
            model_name='appdevuser',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Candidate'),
        ),
        migrations.AddField(
            model_name='appdevuser',
            name='ideas',
            field=models.ManyToManyField(to='applications.Idea'),
        ),
        migrations.AddField(
            model_name='appdevuser',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Trainee'),
        ),
    ]
