# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 19:27
from __future__ import unicode_literals

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='scores',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='appdevuser',
            name='on_email_list',
            field=models.BooleanField(default=False, verbose_name='On Email List?'),
        ),
        migrations.AlterField(
            model_name='appdevuser',
            name='portfolio_link',
            field=models.CharField(default='', max_length=200, verbose_name='Portfolio Link'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='essay',
            field=models.CharField(blank=True, default='', max_length=100000, validators=[applications.models.validate_essay_length], verbose_name='Candidate Essay'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('DES', 'Designer'), ('DEV', 'Developer')], default='DEV', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='access_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Rand64 Access Code'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='essay',
            field=models.CharField(blank=True, default='', max_length=100000, validators=[applications.models.validate_essay_length], verbose_name='Trainee Essay'),
        ),
    ]
