# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20160116_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevuser',
            name='submitted_ct',
            field=models.BooleanField(default=False, verbose_name='Submitted Core Team App?'),
        ),
        migrations.AddField(
            model_name='appdevuser',
            name='submitted_tp',
            field=models.BooleanField(default=False, verbose_name='Submitted Training Program App?'),
        ),
    ]
